# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Data type version
version: 2

# Personal info
name: Joonghoo Park
title: Graduate Student
email: pjh98@korea.ac.kr
website: www.github.com/Hoovely

# Dark Mode (true/false/never)
darkmode: false

# Additional icon links
additional_links:
- title: Github Link
  icon: fab fa-github
  url: https://www.github.com/Hoovely
- title: Linkedin Link
  icon: fab fa-linkedin
  url: https://www.linkedin.com/
- title: Google Scholar Link
  icon: fab fa-google
  url: https://scholar.google.com/

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/JH.jpg
about_content: > # this means to ignore newlines until the next config item.
  Hi! My name is Joonghoo Park.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Korea University
        border: weak
        # sub_title: 2023 - 2025
        caption: 2023 - 2025
        description: | # this will include new lines to allow paragraphs
          M.S. in Industrial Management Engineering
      - layout: left
        title: Pusan National University
        border: weak
        # sub_title: 2017 - 2023
        caption: 2017 - 2023
        description: | # this will include new lines to allow paragraphs
          B.S. in Urban Engineering (Double: Big Data Science)

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Bigdata Analytics & Engineering Lab
        # sub_title: Research Intern
        caption: 2022 - 2023
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          Research Intern at Bigdata Analytics & Engineering Lab, Pusan National University
      - layout: left
        title: Regional Development & Planning Lab
        # sub_title: Research Intern
        caption: 2021 - 2022
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          Research Intern at Regional Development & Planning Lab, Pusan National University
      
  - title: Publications
    layout: list
    content:
      - layout: top-left
        title: International Journals
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          - (Works in Progress) Hyungjoo Cha, Joonghoo Park, Chungmok Lee* and Taesu Cheong*, "Branch and cut algorithm for vehicle routing problem with availability profiles"
          - (Works in Progress) Joonghoo Park, Gwangjong Ko, Hyungjoo Cha and Taesu Cheong*, “Vehicle routing problem with metro based backhauls and MFCs”
          - (Works in Progress) Joonghoo Park, Hyungjoo Cha, San Kwon and Taesu Cheong*, “Temporary medical shelter location-routing problem with manpower allocation in a disaster situation”
          - Seongjin Lee, Joonghoo Park, Seungmin Cha and Donghyun Kim* (2022), “A Regional Economy’s Resistance to the COVID-19 Shock: Sales Revenues of Micro-, Small-, and Medium-Sized Enterprises in South Korea”, International Journal of Disaster Risk Science
        position: top-left

  - title: Conferences
    layout: list
    content:
      - layout: top-left
        title: International Conferences
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          - Joonghoo Park, Hyungjoo Cha, San Kwon and Taesu Cheong*, “Temporary medical shelter location-routing problem with manpower allocation in a disaster situation”, 2024 INFORMS Annual Meeting, Nov 2024.
          - Joonghoo Park, Gwangjong Ko and Taesu Cheong*, “Micro-fulfillment center location routing problem with underground logistics system”, 2024 International Conference of Asian Shipping and Logistics, Jun 2024.
        position: top-left

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Samsung Display
        caption: Mar. 2024 - Present
        description: | # this will include new lines to allow paragraphs
          Optimize facility planning by using optimization, Research Assistant @ Korea University
      - layout: left
        title: IITP
        caption: Feb. 2024 - Present
        description: | # this will include new lines to allow paragraphs
          Development of NetZero Building Energy Efficient System through AI-based HVAC system control, Information and Communication Planning and Evaluation Institute, Research Assistant @ Korea University 
      - layout: left
        title: Samsung Electronics
        caption: Nov. 2023 - Feb. 2024
        description: | # this will include new lines to allow paragraphs
          Maximize productivity by changing facility and logistics layouts Model development, Research Assistant @ Korea University
  
  - title: Scholarship
    layout: list
    content:
      - layout: left
        title: Korea University
        description: | # this will include new lines to allow paragraphs
          Graduate School Mentor-Mentee Program, 2024
      - layout: left
        title: Korea University
        description: | # this will include new lines to allow paragraphs
          Future Talent Scholarship Student, 2023
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag